### PR TITLE
Add option for lastLogin

### LINKED ISSUE #22: Add last login time to the report.
I know its not strictly 'usage', but it does tell admins if he user is 'using' Nextcloud.
Don't know if it's possible but it is in the users view on the web console, so the info is somewhere.
Thanks.

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #22 

cc @derekblankmccoy if you want to test this before I make a new release

### CODE REVIEW

**Comment by derekblankmccoy** [comment]
@nickvergessen Do I just download the zip and cp the contents over to the apps directory?

**Comment by nickvergessen** [comment]
[user_usage_report.tar.gz](https://github.com/nextcloud/user_usage_report/files/2621192/user_usage_report.tar.gz)

You can test the package above

**Comment by derekblankmccoy** [comment]
[Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "usage-report" namespace.

**Comment by nickvergessen** [comment]
Did you enable the app?

**Comment by derekblankmccoy** [comment]
App "User usage report" cannot be installed because it is not compatible with this version of the server.

I'm on 13.0.4

**Comment by nickvergessen** [comment]
ah okay

**Comment by derekblankmccoy** [comment]
The current version on the app works. Should I upgrade to 14.0.4?
I'm happy with 13.04 as it seems to be the most sable version Ive had.

**Pull request merged**
